/**
 * HTTP Status Code Enum
 * Standard HTTP response status codes for consistent API responses.
 */
enum STATUS_CODE {
    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NO_CONTENT = 204,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    CONFLICT = 409,
    UNPROCESSABLE_ENTITY = 422,
    TOO_MANY_REQUESTS = 429,
    INTERNAL_SERVER_ERROR = 500,
    BAD_GATEWAY = 502,
    SERVICE_UNAVAILABLE = 503,
    GATEWAY_TIMEOUT = 504,
}

module.exports = {
    HTTP_STATUS: STATUS_CODE,
    HTTP_STATUS_2XX: [STATUS_CODE.OK, STATUS_CODE.CREATED, STATUS_CODE.ACCEPTED, STATUS_CODE.NO_CONTENT],
    HTTP_SUCCES_STATUSES: [
        STATUS_CODE.OK,
        STATUS_CODE.CREATED,
        STATUS_CODE.ACCEPTED,
        STATUS_CODE.NO_CONTENT,
    ]
};
